package plc_mms.sop_corba.GestionPlcTuPackage;


/**
* plc_mms/sop_corba/GestionPlcTuPackage/DatosPlcTu_DTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

public final class DatosPlcTu_DTO implements org.omg.CORBA.portable.IDLEntity
{
  public String id_plctu = null;
  public String propietario = null;
  public String tipoIden = null;
  public String numIden = null;
  public String direccion = null;
  public String estrato = null;
  public String fechaRegistro = null;
  public int lectura = (int)0;
  public int consumo = (int)0;

  public DatosPlcTu_DTO ()
  {
  } // ctor

  public DatosPlcTu_DTO (String _id_plctu, String _propietario, String _tipoIden, String _numIden, String _direccion, String _estrato, String _fechaRegistro, int _lectura, int _consumo)
  {
    id_plctu = _id_plctu;
    propietario = _propietario;
    tipoIden = _tipoIden;
    numIden = _numIden;
    direccion = _direccion;
    estrato = _estrato;
    fechaRegistro = _fechaRegistro;
    lectura = _lectura;
    consumo = _consumo;
  } // ctor

} // class DatosPlcTu_DTO
