package plc_mms.sop_corba.GestionPlcTuPackage;


/**
* plc_mms/sop_corba/GestionPlcTuPackage/Factura_DTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

public final class Factura_DTO implements org.omg.CORBA.portable.IDLEntity
{
  public String id_plctu = null;
  public String lecturaIni = null;
  public String lecturaFin = null;
  public int consumo = (int)0;

  public Factura_DTO ()
  {
  } // ctor

  public Factura_DTO (String _id_plctu, String _lecturaIni, String _lecturaFin, int _consumo)
  {
    id_plctu = _id_plctu;
    lecturaIni = _lecturaIni;
    lecturaFin = _lecturaFin;
    consumo = _consumo;
  } // ctor

} // class Factura_DTO
