package plc_mms.sop_corba.GestionPlcTuPackage;

/**
* plc_mms/sop_corba/GestionPlcTuPackage/Factura_DTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

public final class Factura_DTOHolder implements org.omg.CORBA.portable.Streamable
{
  public plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO value = null;

  public Factura_DTOHolder ()
  {
  }

  public Factura_DTOHolder (plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTOHelper.type ();
  }

}
