package plc_mms.sop_corba.GestionPlcTuPackage;


/**
* plc_mms/sop_corba/GestionPlcTuPackage/Factura_DTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

abstract public class Factura_DTOHelper
{
  private static String  _id = "IDL:sop_corba/GestionPlcTu/Factura_DTO:1.0";

  public static void insert (org.omg.CORBA.Any a, plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id_plctu",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "lecturaIni",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "lecturaFin",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "consumo",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTOHelper.id (), "Factura_DTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO read (org.omg.CORBA.portable.InputStream istream)
  {
    plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO value = new plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO ();
    value.id_plctu = istream.read_string ();
    value.lecturaIni = istream.read_string ();
    value.lecturaFin = istream.read_string ();
    value.consumo = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, plc_mms.sop_corba.GestionPlcTuPackage.Factura_DTO value)
  {
    ostream.write_string (value.id_plctu);
    ostream.write_string (value.lecturaIni);
    ostream.write_string (value.lecturaFin);
    ostream.write_long (value.consumo);
  }

}
