package plc_mms.sop_corba.GestionPlcTuPackage;


/**
* plc_mms/sop_corba/GestionPlcTuPackage/ListaDto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

public final class ListaDto implements org.omg.CORBA.portable.IDLEntity
{
  public plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTO listTU[] = null;

  public ListaDto ()
  {
  } // ctor

  public ListaDto (plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTO[] _listTU)
  {
    listTU = _listTU;
  } // ctor

} // class ListaDto
