package plc_tu.sop_corba.GestionAlertasPackage;

/**
* plc_tu/sop_corba/GestionAlertasPackage/alertaDtoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesalertas.idl
* martes 28 de mayo de 2024 05:03:02 PM COT
*/

public final class alertaDtoHolder implements org.omg.CORBA.portable.Streamable
{
  public plc_tu.sop_corba.GestionAlertasPackage.alertaDto value = null;

  public alertaDtoHolder ()
  {
  }

  public alertaDtoHolder (plc_tu.sop_corba.GestionAlertasPackage.alertaDto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = plc_tu.sop_corba.GestionAlertasPackage.alertaDtoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    plc_tu.sop_corba.GestionAlertasPackage.alertaDtoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return plc_tu.sop_corba.GestionAlertasPackage.alertaDtoHelper.type ();
  }

}
