package plc_mms.sop_corba;


/**
* plc_mms/sop_corba/GestionPlcTu.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

public interface GestionPlcTu extends GestionPlcTuOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPlcTu
