package plc_mms.sop_corba;


/**
* plc_mms/sop_corba/GestionUsuariosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesusuarios.idl
* jueves 6 de junio de 2024 12:24:04 PM COT
*/

public abstract class GestionUsuariosPOA extends org.omg.PortableServer.Servant
 implements plc_mms.sop_corba.GestionUsuariosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("abrirSesion", new java.lang.Integer (0));
    _methods.put ("consultarUsuario", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionUsuarios/abrirSesion
       {
         plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTO objUsuario = plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTOHelper.read (in);
         int $result = (int)0;
         $result = this.abrirSesion (objUsuario);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // sop_corba/GestionUsuarios/consultarUsuario
       {
         int id = in.read_long ();
         plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTOHolder objUsuario = new plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTOHolder ();
         boolean $result = false;
         $result = this.consultarUsuario (id, objUsuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTOHelper.write (out, objUsuario.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionUsuarios:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionUsuarios _this() 
  {
    return GestionUsuariosHelper.narrow(
    super._this_object());
  }

  public GestionUsuarios _this(org.omg.CORBA.ORB orb) 
  {
    return GestionUsuariosHelper.narrow(
    super._this_object(orb));
  }


} // class GestionUsuariosPOA
