package plc_mms.sop_corba;


/**
* sop_corba/GestionUsuarios.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesusuarios.idl
* martes 14 de mayo de 2024 05:34:09 PM COT
*/

public interface GestionUsuarios extends GestionUsuariosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionUsuarios
