package plc_mms.sop_corba;


/**
* sop_corba/GestionPlcTu.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* martes 21 de mayo de 2024 03:52:35 PM COT
*/

public interface GestionPlcTu extends GestionPlcTuOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPlcTu
