package plc_mms.sop_corba;

/**
* sop_corba/GestionUsuariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesusuarios.idl
* martes 14 de mayo de 2024 05:34:09 PM COT
*/

public final class GestionUsuariosHolder implements org.omg.CORBA.portable.Streamable
{
  public plc_mms.sop_corba.GestionUsuarios value = null;

  public GestionUsuariosHolder ()
  {
  }

  public GestionUsuariosHolder (plc_mms.sop_corba.GestionUsuarios initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = plc_mms.sop_corba.GestionUsuariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    plc_mms.sop_corba.GestionUsuariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return plc_mms.sop_corba.GestionUsuariosHelper.type ();
  }

}
