package plc_mms.sop_corba;


/**
* sop_corba/GestionPlcTuOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* martes 21 de mayo de 2024 03:52:35 PM COT
*/

public interface GestionPlcTuOperations 
{
  boolean registrar_plctu (plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTO dplctu);
  boolean consultarplctu (int plctuid, plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTOHolder objTU);
} // interface GestionPlcTuOperations
