package sop_corba.GestionPlcTuPackage;


/**
* sop_corba/GestionPlcTuPackage/DatosPlcTu_DTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* martes 28 de mayo de 2024 04:59:13 PM COT
*/

public final class DatosPlcTu_DTO implements org.omg.CORBA.portable.IDLEntity
{
  public String id_plctu = null;
  public String propietario = null;
  public String direccion = null;
  public int consumo = (int)0;

  public DatosPlcTu_DTO ()
  {
  } // ctor

  public DatosPlcTu_DTO (String _id_plctu, String _propietario, String _direccion, int _consumo)
  {
    id_plctu = _id_plctu;
    propietario = _propietario;
    direccion = _direccion;
    consumo = _consumo;
  } // ctor

} // class DatosPlcTu_DTO
