package plc_mms.sop_corba.GestionPlcTuPackage;

/**
* plc_mms/sop_corba/GestionPlcTuPackage/DatosPlcTu_DTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* martes 28 de mayo de 2024 05:03:03 PM COT
*/

public final class DatosPlcTu_DTOHolder implements org.omg.CORBA.portable.Streamable
{
  public plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTO value = null;

  public DatosPlcTu_DTOHolder ()
  {
  }

  public DatosPlcTu_DTOHolder (plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return plc_mms.sop_corba.GestionPlcTuPackage.DatosPlcTu_DTOHelper.type ();
  }

}
