/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionSaa.h"

void *
notificarplcmms_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	int varIdMMs = *argp / 100;
	int varIdTu = *argp % 100; 

	printf("El dispositivo PLC_MMS con id: %d completo sus registro y esta activo en el sistema\n", *argp);
	registrarEnArchivo(varIdMMs,varIdTu);
	return (void *) &result;
}



void registrarEnArchivo(int prmMMS , int prmTU) {
    FILE *archivo;
    char nombreArchivo[13]; // +5 para espacio adicional y extensión .txt
    sprintf(nombreArchivo, "id%d_id%d.txt", prmMMS,prmTU); // Nombre del archivo es el id_plctu con extensión .txt
   
    archivo = fopen(nombreArchivo, "w"); // Abre el archivo en modo "escritura" (write)
    printf("Se abrio el archivo %s", nombreArchivo);

    if (archivo == NULL) {
        printf("Error al abrir el archivo.\n");
        return;
    }
    fclose(archivo);
    
    printf("Se guardo el archivo %s", nombreArchivo);
}
