/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONPLCTU_H_RPCGEN
#define _GESTIONPLCTU_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXID 8
#define MAXCAD 64
#define MAXTP 3
#define MAXNUMID 15

struct datos_plctu {
	char id_plctu[MAXID];
	char propietario[MAXCAD];
	char tipo_iden[MAXTP];
	char num_iden[MAXNUMID];
	char direccion[MAXCAD];
	int estrato;
	char fecha_registro[MAXCAD];
	int consumo;
};
typedef struct datos_plctu datos_plctu;

#define gestion_dispositivos 0x30000015
#define gestion_dispositivos_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrar_plctu 1
extern  bool_t * registrar_plctu_1(datos_plctu *, CLIENT *);
extern  bool_t * registrar_plctu_1_svc(datos_plctu *, struct svc_req *);
#define consultar_plctu 2
extern  datos_plctu * consultar_plctu_1(int *, CLIENT *);
extern  datos_plctu * consultar_plctu_1_svc(int *, struct svc_req *);
extern int gestion_dispositivos_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrar_plctu 1
extern  bool_t * registrar_plctu_1();
extern  bool_t * registrar_plctu_1_svc();
#define consultar_plctu 2
extern  datos_plctu * consultar_plctu_1();
extern  datos_plctu * consultar_plctu_1_svc();
extern int gestion_dispositivos_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos_plctu (XDR *, datos_plctu*);

#else /* K&R C */
extern bool_t xdr_datos_plctu ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONPLCTU_H_RPCGEN */
