package grsaa.sop_corba;

/**
* grsaa/sop_corba/GestionDispositivosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* martes 28 de mayo de 2024 05:03:04 PM COT
*/

public final class GestionDispositivosHolder implements org.omg.CORBA.portable.Streamable
{
  public grsaa.sop_corba.GestionDispositivos value = null;

  public GestionDispositivosHolder ()
  {
  }

  public GestionDispositivosHolder (grsaa.sop_corba.GestionDispositivos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = grsaa.sop_corba.GestionDispositivosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    grsaa.sop_corba.GestionDispositivosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return grsaa.sop_corba.GestionDispositivosHelper.type ();
  }

}
