package grsaa.sop_corba;


/**
* grsaa/sop_corba/GestionDispositivosPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* martes 21 de mayo de 2024 05:08:23 PM COT
*/

public class GestionDispositivosPOATie extends GestionDispositivosPOA
{

  // Constructors

  public GestionDispositivosPOATie ( grsaa.sop_corba.GestionDispositivosOperations delegate ) {
      this._impl = delegate;
  }
  public GestionDispositivosPOATie ( grsaa.sop_corba.GestionDispositivosOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public grsaa.sop_corba.GestionDispositivosOperations _delegate() {
      return this._impl;
  }
  public void _delegate (grsaa.sop_corba.GestionDispositivosOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void notificacionmms (grsaa.sop_corba.GestionDispositivosPackage.notificacionDTO objNotificacion)
  {
    _impl.notificacionmms(objNotificacion);
  } // notificacionmms

  private grsaa.sop_corba.GestionDispositivosOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionDispositivosPOATie
