package grsaa.sop_corba;


/**
* grsaa/sop_corba/GestionDispositivosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* martes 28 de mayo de 2024 05:03:04 PM COT
*/

public interface GestionDispositivosOperations 
{
  void notificacionmms (grsaa.sop_corba.GestionDispositivosPackage.notificacionDTO objNotificacion);
} // interface GestionDispositivosOperations
