package grsaa.sop_corba;


/**
* grsaa/sop_corba/GestionDispositivos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* martes 28 de mayo de 2024 05:03:04 PM COT
*/

public interface GestionDispositivos extends GestionDispositivosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionDispositivos
