package plc_tu.sop_corba;


/**
* plc_tu/sop_corba/GestionAlertas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesalertas.idl
* martes 28 de mayo de 2024 05:03:02 PM COT
*/

public interface GestionAlertas extends GestionAlertasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionAlertas
