package plc_tu.sop_corba;


/**
* plc_tu/sop_corba/GestionAlertasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesalertas.idl
* martes 28 de mayo de 2024 05:03:02 PM COT
*/

public interface GestionAlertasOperations 
{
  void notificar (plc_tu.sop_corba.GestionAlertasPackage.alertaDto objAlerta);
} // interface GestionAlertasOperations
