package plc_tu.sop_corba;


/**
* plc_tu/sop_corba/GestionAlertasPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesalertas.idl
* martes 28 de mayo de 2024 05:03:02 PM COT
*/

public abstract class GestionAlertasPOA extends org.omg.PortableServer.Servant
 implements plc_tu.sop_corba.GestionAlertasOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notificar", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionAlertas/notificar
       {
         plc_tu.sop_corba.GestionAlertasPackage.alertaDto objAlerta = plc_tu.sop_corba.GestionAlertasPackage.alertaDtoHelper.read (in);
         this.notificar (objAlerta);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionAlertas:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionAlertas _this() 
  {
    return GestionAlertasHelper.narrow(
    super._this_object());
  }

  public GestionAlertas _this(org.omg.CORBA.ORB orb) 
  {
    return GestionAlertasHelper.narrow(
    super._this_object(orb));
  }


} // class GestionAlertasPOA
