package plc_tu.sop_corba;


/**
* plc_tu/sop_corba/GestionAlertasHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesalertas.idl
* martes 28 de mayo de 2024 05:03:02 PM COT
*/

abstract public class GestionAlertasHelper
{
  private static String  _id = "IDL:sop_corba/GestionAlertas:1.0";

  public static void insert (org.omg.CORBA.Any a, plc_tu.sop_corba.GestionAlertas that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static plc_tu.sop_corba.GestionAlertas extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (plc_tu.sop_corba.GestionAlertasHelper.id (), "GestionAlertas");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static plc_tu.sop_corba.GestionAlertas read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionAlertasStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, plc_tu.sop_corba.GestionAlertas value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static plc_tu.sop_corba.GestionAlertas narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof plc_tu.sop_corba.GestionAlertas)
      return (plc_tu.sop_corba.GestionAlertas)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      plc_tu.sop_corba._GestionAlertasStub stub = new plc_tu.sop_corba._GestionAlertasStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static plc_tu.sop_corba.GestionAlertas unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof plc_tu.sop_corba.GestionAlertas)
      return (plc_tu.sop_corba.GestionAlertas)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      plc_tu.sop_corba._GestionAlertasStub stub = new plc_tu.sop_corba._GestionAlertasStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
