package grsaa.sop_corba.GestionDispositivosPackage;


/**
* grsaa/sop_corba/GestionDispositivosPackage/notificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* martes 28 de mayo de 2024 05:03:04 PM COT
*/

public final class notificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int idPlcmms = (int)0;

  public notificacionDTO ()
  {
  } // ctor

  public notificacionDTO (int _idPlcmms)
  {
    idPlcmms = _idPlcmms;
  } // ctor

} // class notificacionDTO
