/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionSaa.h"

void *
notificarplcmms_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("El dispositivo PLC_MMS con id: %d completo sus registro y esta activo en el sistema\n", *argp);

	return (void *) &result;
}
