package sop_corba;

/**
* sop_corba/GestionPlcTuHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* martes 28 de mayo de 2024 04:59:13 PM COT
*/

public final class GestionPlcTuHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionPlcTu value = null;

  public GestionPlcTuHolder ()
  {
  }

  public GestionPlcTuHolder (sop_corba.GestionPlcTu initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionPlcTuHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionPlcTuHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionPlcTuHelper.type ();
  }

}
