package sop_corba;


/**
* sop_corba/GestionPlcTuOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* martes 28 de mayo de 2024 04:59:13 PM COT
*/

public interface GestionPlcTuOperations 
{
  boolean registrar_plctu (sop_corba.GestionPlcTuPackage.DatosPlcTu_DTO dplctu);
  boolean consultarplctu (int plctuid, sop_corba.GestionPlcTuPackage.DatosPlcTu_DTOHolder objTU);
  void registrarCallback (sop_corba.GestionAlertas objAlertas);
} // interface GestionPlcTuOperations
