package plc_mms.sop_corba.GestionUsuariosPackage;

/**
* plc_mms/sop_corba/GestionUsuariosPackage/usuarioDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesusuarios.idl
* jueves 6 de junio de 2024 12:24:04 PM COT
*/

public final class usuarioDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTO value = null;

  public usuarioDTOHolder ()
  {
  }

  public usuarioDTOHolder (plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return plc_mms.sop_corba.GestionUsuariosPackage.usuarioDTOHelper.type ();
  }

}
