package grsaa.sop_corba;


/**
* grsaa/sop_corba/GestionDispositivosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* martes 21 de mayo de 2024 05:08:23 PM COT
*/

abstract public class GestionDispositivosHelper
{
  private static String  _id = "IDL:sop_corba/GestionDispositivos:1.0";

  public static void insert (org.omg.CORBA.Any a, grsaa.sop_corba.GestionDispositivos that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static grsaa.sop_corba.GestionDispositivos extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (grsaa.sop_corba.GestionDispositivosHelper.id (), "GestionDispositivos");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static grsaa.sop_corba.GestionDispositivos read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionDispositivosStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, grsaa.sop_corba.GestionDispositivos value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static grsaa.sop_corba.GestionDispositivos narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof grsaa.sop_corba.GestionDispositivos)
      return (grsaa.sop_corba.GestionDispositivos)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      grsaa.sop_corba._GestionDispositivosStub stub = new grsaa.sop_corba._GestionDispositivosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static grsaa.sop_corba.GestionDispositivos unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof grsaa.sop_corba.GestionDispositivos)
      return (grsaa.sop_corba.GestionDispositivos)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      grsaa.sop_corba._GestionDispositivosStub stub = new grsaa.sop_corba._GestionDispositivosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
