package plc_mms.sop_corba;


/**
* plc_mms/sop_corba/GestionPlcTu.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesplctu.idl
* martes 28 de mayo de 2024 05:03:03 PM COT
*/

public interface GestionPlcTu extends GestionPlcTuOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPlcTu
