package plc_mms.sop_corba;


/**
* plc_mms/sop_corba/GestionUsuarios.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesusuarios.idl
* martes 28 de mayo de 2024 05:03:03 PM COT
*/

public interface GestionUsuarios extends GestionUsuariosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionUsuarios
