package grsaa.sop_corba;


/**
* grsaa/sop_corba/GestionDispositivosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

public abstract class GestionDispositivosPOA extends org.omg.PortableServer.Servant
 implements grsaa.sop_corba.GestionDispositivosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notificacionmms", new java.lang.Integer (0));
    _methods.put ("lectura", new java.lang.Integer (1));
    _methods.put ("recuperarFactura", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionDispositivos/notificacionmms
       {
         grsaa.sop_corba.GestionDispositivosPackage.notificacionDTO objNotificacion = grsaa.sop_corba.GestionDispositivosPackage.notificacionDTOHelper.read (in);
         this.notificacionmms (objNotificacion);
         out = $rh.createReply();
         break;
       }

       case 1:  // sop_corba/GestionDispositivos/lectura
       {
         grsaa.sop_corba.GestionDispositivosPackage.Lectura_DTOHolder objLectura = new grsaa.sop_corba.GestionDispositivosPackage.Lectura_DTOHolder ();
         objLectura.value = grsaa.sop_corba.GestionDispositivosPackage.Lectura_DTOHelper.read (in);
         int $result = (int)0;
         $result = this.lectura (objLectura);
         out = $rh.createReply();
         out.write_long ($result);
         grsaa.sop_corba.GestionDispositivosPackage.Lectura_DTOHelper.write (out, objLectura.value);
         break;
       }

       case 2:  // sop_corba/GestionDispositivos/recuperarFactura
       {
         String IdTu = in.read_string ();
         grsaa.sop_corba.GestionDispositivosPackage.Factura_DTOHolder objFactura = new grsaa.sop_corba.GestionDispositivosPackage.Factura_DTOHolder ();
         boolean $result = false;
         $result = this.recuperarFactura (IdTu, objFactura);
         out = $rh.createReply();
         out.write_boolean ($result);
         grsaa.sop_corba.GestionDispositivosPackage.Factura_DTOHelper.write (out, objFactura.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionDispositivos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionDispositivos _this() 
  {
    return GestionDispositivosHelper.narrow(
    super._this_object());
  }

  public GestionDispositivos _this(org.omg.CORBA.ORB orb) 
  {
    return GestionDispositivosHelper.narrow(
    super._this_object(orb));
  }


} // class GestionDispositivosPOA
