package grsaa.sop_corba;


/**
* grsaa/sop_corba/GestionDispositivosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

public interface GestionDispositivosOperations 
{
  void notificacionmms (grsaa.sop_corba.GestionDispositivosPackage.notificacionDTO objNotificacion);
  int lectura (grsaa.sop_corba.GestionDispositivosPackage.Lectura_DTOHolder objLectura);
  boolean recuperarFactura (String IdTu, grsaa.sop_corba.GestionDispositivosPackage.Factura_DTOHolder objFactura);
} // interface GestionDispositivosOperations
