package grsaa.sop_corba;


/**
* grsaa/sop_corba/GestionDispositivos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesdispositivos.idl
* jueves 6 de junio de 2024 12:24:05 PM COT
*/

public interface GestionDispositivos extends GestionDispositivosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionDispositivos
